---
steps:
  - label: ":bazel: source build"
    timeout: 5
    agents:
      lyft:fleet:buildkite: cpu
    command: >
      apt-get update &&
      apt-get install -y openjdk-8-jdk python unzip zip ca-certificates &&
      echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list &&
      curl https://bazel.build/bazel-release.pub.gpg | apt-key add - &&
      apt-get update &&
      apt-get install -y bazel &&
      bazel build //src:bazel &&
      ls -lah bazel-bin/src
    artifact_paths:
      - /workdir/bazel-bin/src/bazel
    plugins:
      docker#v1.1.1:
        image: phusion/baseimage:latest
        workdir: /workdir
        environment:
          - BUILDKITE_BRANCH=${BUILDKITE_BRANCH}
          - BUILDKITE=true

  - wait

  - label: publish
    command: buildkite-agent artifact download /workdir/bazel-bin/src/bazel . && stat bazel
    timeout: 5
    agents:
      lyft:fleet:buildkite: cpu
    plugins:
      docker#v1.1.1:
        image: phusion/baseimage:latest
        workdir: /workdir
        environment:
          - BUILDKITE_BRANCH=${BUILDKITE_BRANCH}
          - BUILDKITE=true
